pipeline:
  name: tomcatnew
  identifier: tomcatnew
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: tomcatnew
        identifier: tomcatnew
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Tomcat
          environment:
            environmentRef: harnessdevenvdep
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnessk8sinfradep
          execution:
            steps:
              - step:
                  type: K8sDryRun
                  name: K8sDryRun_1
                  identifier: K8sDryRun_1
                  spec: {}
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
