pipeline:
  name: tomcatsecret
  identifier: tomcatsecret
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Tomcat
        identifier: Tomcat
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          #!/bin/bash
                          pwd
                          kubectl apply -f /Users/balakumaar/harnesscd-example-apps/helm-guestbook/harnesscd-pipeline/testsecret.yaml -n default
                          git clone https://github.com/balakumaar1653/harnesscd-example-apps.git
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
